### ISSUE TITLE
we need better tests that actually test the existing templates

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/beetmoverscript#58]
To prevent situations like this: https://public-artifacts.taskcluster.net/HrTLb_wUSzauU7so9BXYwQ/2/public/logs/live_backing.log

2017-03-17 23:18:29,390 - asyncio - DEBUG - Using selector: EpollSelector
2017-03-17 23:18:29,392 - asyncio - ERROR - Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f2cffe75940>
2017-03-17 23:18:29,395 - beetmoverscript.task - DEBUG - {'type': 'object', 'required': ['payload', 'dependencies'], 'title': 'Taskcluster beetmover task minimal schema', 'properties': {'payload': {'optional': ['build_number', 'version'], 'type': 'object', 'required': ['upload_date', 'upstreamArtifacts'], 'properties': {'upstreamArtifacts': {'items': {'type': 'object', 'required': ['taskId', 'taskType', 'paths', 'locale'], 'properties': {'taskType': {'type': 'string'}, 'locale': {'type': 'string'}, 'paths': {'items': {'type': 'string'}, 'minItems': 1, 'type': 'array', 'uniqueItems': True}, 'taskId': {'type': 'string'}}}, 'minItems': 1, 'type': 'array', 'uniqueItems': True}, 'version': {'type': 'string'}, 'build_number': {'type': 'number'}, 'upload_date': {'type': 'number'}}}, 'dependencies': {'items': {'type': 'string'}, 'minItems': 1, 'type': 'array', 'uniqueItems': True}}}
2017-03-17 23:18:29,398 - beetmoverscript.task - INFO - Buckets: ['nightly']
2017-03-17 23:18:29,399 - beetmoverscript.task - INFO - Action types: ['push-to-nightly']
2017-03-17 23:18:29,400 - beetmoverscript.utils - INFO - generating manifest from: /builds/scriptworker/lib/python3.5/site-packages/beetmoverscript/templates/fennec_nightly.yml
2017-03-17 23:18:29,401 - beetmoverscript.utils - INFO - /builds/scriptworker/lib/python3.5/site-packages/beetmoverscript/templates/fennec_nightly.yml
Traceback (most recent call last):
  File "/builds/scriptworker/bin/beetmoverscript", line 9, in <module>
    load_entry_point('beetmoverscript==0.4.3', 'console_scripts', 'beetmoverscript')()
  File "/builds/scriptworker/lib/python3.5/site-packages/beetmoverscript/script.py", line 272, in main
    loop.run_until_complete(async_main(context))
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/tools/python35/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/tools/python35/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/builds/scriptworker/lib/python3.5/site-packages/beetmoverscript/script.py", line 104, in async_main
    await action_map[context.action](context)
  File "/builds/scriptworker/lib/python3.5/site-packages/beetmoverscript/script.py", line 41, in push_to_nightly
    mapping_manifest = generate_beetmover_manifest(context)
  File "/builds/scriptworker/lib/python3.5/site-packages/beetmoverscript/utils.py", line 111, in generate_beetmover_manifest
    manifest = yaml.safe_load(tmpl.render(**tmpl_args))
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/builds/scriptworker/lib/python3.5/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 81, column 5:
        target.awsy.tests.zip
        ^
could not find expected ':'
  in "<unicode string>", line 82, column 13:
          s3_key: fennec-55.0a1.multi.android-ar ... 
                ^
exit code: 1

**Comment by MihaiTabara** [comment]
Duplicate of https://github.com/mozilla-releng/beetmoverscript/issues/116
